model:
  type: unetmini
dataset: reduced_gta5
cutout: 80
batch: 128
epoch: 200
aug: default
lr: 0.1
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 1
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0002
  ema: 0
class_weighting: enet
task: segmentation
ignore_label: 19