model:
  type: unetmini
dataset: reduced_gta5
cutout: 80
batch: 4
epoch: 200
aug: default
lr: 0.005
lr_schedule:
  type: 'none'
  warmup:
    multiplier: 1
    epoch: 5
optimizer:
  type: adam
  decay: 0.0002
  ema: 0
class_weighting: enet
task: segmentation
ignore_label: 19